### ISSUE TITLE
bsh-aws-ses-send no longer exists in npm

### ISSUE THREAD

**Issue by pward123** [FranzZemen/bsh-aws-ses-send#2]
Started getting yarn 404 errors trying to download this package and I can't find it in npm anymore.

**Comment by FranzZemen** [comment]
It has been discontinued.

Do you have a critical need?  I can provide the source if so.

**Comment by pward123** [comment]
is master the same as 0.2.3? If so, I can just grab the code here.

**Comment by FranzZemen** [comment]
Master should work.  It really hasn't changed in years.
